# Generated by Django 3.1.7 on 2021-03-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_Sys', '0003_auto_20210318_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='percentage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
