# Generated by Django 3.1.7 on 2021-03-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_Sys', '0004_auto_20210319_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
