# Generated by Django 3.1.7 on 2021-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_Sys', '0005_auto_20210319_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='branch',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='section',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
