# Generated by Django 3.1.7 on 2021-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence_Sys', '0006_auto_20210319_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
